/**
 * 법제처 OpenAPI 경로 정의
 */

import { apiPath, idParam, jsonResponse, param, searchParams, searchTypeParam } from "./shared.js";
import type { OpenApiPaths } from "./shared.js";

export function getLawPaths(): OpenApiPaths {
  return {
    ...apiPath({
      path: "/api/search/laws",
      operationId: "searchLaws",
      summary: "법령 검색",
      description: "대한민국 현행 법령(법률, 대통령령, 부령 등)을 키워드로 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display, searchTypeParam("검색 범위")],
      responses: jsonResponse("법령 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/cases",
      operationId: "searchCases",
      summary: "판례 검색",
      description: "대법원/하급법원 판례를 키워드로 검색합니다.",
      parameters: [
        searchParams.query,
        searchParams.page,
        searchParams.display,
        param("search_type", "검색 범위", {
          schema: { type: "string", enum: ["case_name", "full_text"], default: "full_text" },
        }),
        param("date_from", "시작일 (YYYYMMDD)", { schema: { type: "string", pattern: "^\\d{8}$" } }),
        param("date_to", "종료일 (YYYYMMDD)", { schema: { type: "string", pattern: "^\\d{8}$" } }),
        param("court", "법원 유형", {
          schema: { type: "string", enum: ["supreme", "lower", "all"], default: "all" },
        }),
      ],
      responses: jsonResponse("판례 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/constitutional",
      operationId: "searchConstitutional",
      summary: "헌재결정례 검색",
      description: "헌법재판소 결정례를 키워드로 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("헌재결정례 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/interpretations",
      operationId: "searchInterpretations",
      summary: "법령해석례 검색",
      description: "법제처 법령해석례를 키워드로 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("법령해석례 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/admin-rules",
      operationId: "searchAdminRules",
      summary: "행정규칙 검색",
      description: "훈령, 예규, 고시 등 행정규칙을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display, searchTypeParam("검색 범위")],
      responses: jsonResponse("행정규칙 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/ordinances",
      operationId: "searchOrdinances",
      summary: "자치법규 검색",
      description: "지방자치단체 조례 및 규칙을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display, searchTypeParam("검색 범위")],
      responses: jsonResponse("자치법규 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/treaties",
      operationId: "searchTreaties",
      summary: "조약 검색",
      description: "대한민국 체결 조약을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("조약 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/legal-terms",
      operationId: "searchLegalTerms",
      summary: "법령용어 검색",
      description: "법령에서 사용되는 용어 정의를 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("법령용어 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/english-laws",
      operationId: "searchEnglishLaws",
      summary: "영문법령 검색",
      description: "한국 법령의 영문 번역본을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display, searchTypeParam("검색 범위")],
      responses: jsonResponse("영문법령 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/committee-decisions",
      operationId: "searchCommitteeDecisions",
      summary: "위원회 결정문 검색",
      description: "행정위원회 결정문을 검색합니다.",
      parameters: [
        searchParams.query,
        searchParams.page,
        searchParams.display,
        param("committee", "위원회 코드", {
          required: true,
          schema: {
            type: "string",
            enum: ["ftc", "acr", "fsc", "nlrc", "kcc", "oclt", "nhrck", "eiac", "ecc", "sfc", "iaciac"],
          },
        }),
      ],
      responses: jsonResponse("위원회 결정문 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/admin-appeals",
      operationId: "searchAdminAppeals",
      summary: "행정심판례 검색",
      description: "행정심판 재결례를 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("행정심판례 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/old-new-law",
      operationId: "searchOldNewLaw",
      summary: "신구법비교 검색",
      description: "법령 개정 전후 조문 비교 목록을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("신구법비교 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/law-system",
      operationId: "searchLawSystem",
      summary: "법령체계도 검색",
      description: "법령의 상위법-하위법 관계 체계도를 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("법령체계도 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/three-way-comp",
      operationId: "searchThreeWayComp",
      summary: "3단비교 검색",
      description: "법률·시행령·시행규칙 3단비교 목록을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("3단비교 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/attached-forms",
      operationId: "searchAttachedForms",
      summary: "별표서식 검색",
      description: "법령의 별표·서식·별지를 검색합니다.",
      parameters: [
        searchParams.query,
        searchParams.page,
        searchParams.display,
        param("form_type", "별표 종류", {
          schema: {
            type: "string",
            enum: ["all", "table", "form", "annex", "other", "unclassified"],
            default: "all",
          },
        }),
      ],
      responses: jsonResponse("별표서식 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/law-abbreviations",
      operationId: "searchLawAbbreviations",
      summary: "법령약칭 검색",
      description: "법령의 약칭 목록을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("법령약칭 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/law-change-history",
      operationId: "searchLawChangeHistory",
      summary: "법령 변경이력 조회",
      description: "특정 일자에 변경된 법령 목록을 조회합니다.",
      parameters: [
        param("date", "변경 일자 (YYYYMMDD)", {
          required: true,
          schema: { type: "string", pattern: "^\\d{8}$" },
        }),
        searchParams.page,
        searchParams.display,
      ],
      responses: jsonResponse("법령 변경이력 결과"),
    }),
    ...apiPath({
      path: "/api/search/ai-legal-terms",
      operationId: "searchAILegalTerms",
      summary: "지식베이스 법령용어 검색",
      description: "법령정보 지식베이스에서 법령용어를 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("지식베이스 법령용어 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/linked-ordinances",
      operationId: "searchLinkedOrdinances",
      summary: "연계조례 검색",
      description: "법령에 연계된 지방자치단체 조례 목록을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("연계조례 검색 결과"),
    }),
    ...apiPath({
      path: "/api/search/admin-rule-old-new",
      operationId: "searchAdminRuleOldNew",
      summary: "행정규칙 신구법비교 검색",
      description: "행정규칙의 개정 전후 비교 목록을 검색합니다.",
      parameters: [searchParams.query, searchParams.page, searchParams.display],
      responses: jsonResponse("행정규칙 신구법비교 검색 결과"),
    }),

    ...apiPath({
      path: "/api/detail/law/{id}",
      operationId: "getLawDetail",
      summary: "법령 상세조회",
      description: "법령 일련번호로 조문 내용을 조회합니다.",
      parameters: [idParam("법령 일련번호")],
      responses: jsonResponse("법령 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/case/{id}",
      operationId: "getCaseDetail",
      summary: "판례 상세조회",
      description: "판례 일련번호로 판시사항, 판결요지, 전문을 조회합니다.",
      parameters: [idParam("판례 일련번호")],
      responses: jsonResponse("판례 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/constitutional/{id}",
      operationId: "getConstitutionalDetail",
      summary: "헌재결정례 상세조회",
      parameters: [idParam("헌재결정례 일련번호")],
      responses: jsonResponse("헌재결정례 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/interpretation/{id}",
      operationId: "getInterpretationDetail",
      summary: "법령해석례 상세조회",
      parameters: [idParam("법령해석례 일련번호")],
      responses: jsonResponse("법령해석례 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/admin-rule/{id}",
      operationId: "getAdminRuleDetail",
      summary: "행정규칙 상세조회",
      parameters: [idParam("행정규칙 일련번호")],
      responses: jsonResponse("행정규칙 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/ordinance/{id}",
      operationId: "getOrdinanceDetail",
      summary: "자치법규 상세조회",
      parameters: [idParam("자치법규 일련번호")],
      responses: jsonResponse("자치법규 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/treaty/{id}",
      operationId: "getTreatyDetail",
      summary: "조약 상세조회",
      parameters: [idParam("조약 일련번호")],
      responses: jsonResponse("조약 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/legal-term/{id}",
      operationId: "getLegalTermDetail",
      summary: "법령용어 상세조회",
      parameters: [idParam("법령용어 일련번호")],
      responses: jsonResponse("법령용어 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/english-law/{id}",
      operationId: "getEnglishLawDetail",
      summary: "영문법령 상세조회",
      parameters: [idParam("영문법령 일련번호")],
      responses: jsonResponse("영문법령 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/committee-decision/{committee}/{id}",
      operationId: "getCommitteeDecisionDetail",
      summary: "위원회 결정문 상세조회",
      parameters: [param("committee", "위원회 코드", { in: "path", schema: { type: "string" } }), idParam("결정문 일련번호")],
      responses: jsonResponse("위원회 결정문 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/admin-appeal/{id}",
      operationId: "getAdminAppealDetail",
      summary: "행정심판례 상세조회",
      parameters: [idParam("행정심판례 일련번호")],
      responses: jsonResponse("행정심판례 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/old-new-law/{id}",
      operationId: "getOldNewLawDetail",
      summary: "신구법비교 상세조회",
      parameters: [idParam("신구법비교 일련번호")],
      responses: jsonResponse("신구법비교 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/law-system/{id}",
      operationId: "getLawSystemDetail",
      summary: "법령체계도 상세조회",
      parameters: [idParam("법령체계도 일련번호")],
      responses: jsonResponse("법령체계도 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/three-way-comp/{id}",
      operationId: "getThreeWayCompDetail",
      summary: "3단비교 상세조회",
      parameters: [
        idParam("3단비교 일련번호"),
        param("comparison_type", "비교 유형", {
          schema: { type: "string", enum: ["citation", "delegation"], default: "citation" },
        }),
      ],
      responses: jsonResponse("3단비교 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/law-article-sub/{id}",
      operationId: "getLawArticleSub",
      summary: "조항호목 정밀조회",
      description: "법령의 특정 조·항·호·목을 정밀하게 조회합니다.",
      parameters: [
        idParam("법령 일련번호"),
        param("article", "조번호 (6자리, 예: 000100)", { required: true, schema: { type: "string" } }),
        param("paragraph", "항번호 (6자리)", { schema: { type: "string" } }),
        param("clause", "호번호 (6자리)", { schema: { type: "string" } }),
        param("subclause", "목번호 (한글 한 글자)", { schema: { type: "string" } }),
      ],
      responses: jsonResponse("조항호목 상세 정보"),
    }),
    ...apiPath({
      path: "/api/detail/admin-rule-old-new/{id}",
      operationId: "getAdminRuleOldNewDetail",
      summary: "행정규칙 신구법비교 상세조회",
      parameters: [idParam("신구법비교 일련번호")],
      responses: jsonResponse("행정규칙 신구법비교 상세 정보"),
    }),
  };
}
